In [7]:
import pandas as pd

In [8]:
cast= pd.read_csv("D:/Data science assignments/Python assignment 4/File/cast.csv")

In [9]:
cast.head()

,title,year,name,type,character,n
0,Closet Monster,2015.0,Buffy #1,actor,Buffy 4,NaN
1,Suuri illusioni,1985.0,Homo $,actor,Guests,22.0
2,Battle of the Sexes,2017.0,$hutter,actor,Bobby Riggs Fan,10.0
3,Secret in Their Eyes,2015.0,$hutter,actor,2002 Dodger Fan,NaN
4,Steve Jobs,2015.0,$hutter,actor,1988 Opera House Patron,NaN

### How many movies are listed in the titles dataframe?

In [11]:
cast["title"].nunique()

166670

### What are the earliest two films listed in the titles dataframe?

In [13]:
df=cast.sort_values(by="year")[["title", "year"]].drop_duplicates().head(2)
df

                         title    year
464860              Miss Jerry  1894.0
1718214  Soldiers of the Cross  1900.0

### How many movies have the title "Hamlet"?

In [15]:
cast[cast["title"]=="Hamlet"]["title"].count()

218

### How many movies are titled "North by Northwest"?

In [17]:
cast[cast["title"]=="North by Northwest"]["title"].count()

81

### When was the first movie titled "Hamlet" made?

In [19]:
cast_sorted=cast.sort_values(by="year")
hamlet_first=cast_sorted[cast_sorted["title"]=="Hamlet"][["title","year"]][0:1]
hamlet_first

          title    year
1545289  Hamlet  1910.0

### List all of the "Treasure Island" movies from earliest to most recent.

In [21]:
treasure_island= cast_sorted[cast_sorted["title"]=="Treasure Island"][["title","year"]]
treasure_island

                   title    year
339256   Treasure Island  1918.0
840745   Treasure Island  1918.0
1473574  Treasure Island  1918.0
1715014  Treasure Island  1918.0
830114   Treasure Island  1918.0
...                  ...     ...
1637661  Treasure Island  1999.0
1797264  Treasure Island  1999.0
1375015  Treasure Island  1999.0
1975279  Treasure Island  1999.0
114904   Treasure Island  1999.0

[154 rows x 2 columns]

### How many movies were made in the year 1950?

In [23]:
cast[cast["year"]==1950]["title"].count()

14653

### How many movies were made in the year 1960?

In [25]:
cast[cast["year"]==1960]["title"].count()

11551

### How many movies were made from 1950 through 1959?

In [27]:
cast[(cast["year"]>=1950) & (cast["year"]<=1959)]["title"].count()

137408

### In what years has a movie titled "Batman" been released?

In [29]:
cast[cast["title"]=="Batman"][["title","year"]]

          title    year
95672    Batman  1943.0
96186    Batman  1943.0
114034   Batman  1989.0
119476   Batman  1989.0
149767   Batman  1989.0
...         ...     ...
2068050  Batman  1989.0
2096318  Batman  1989.0
2099960  Batman  1989.0
2115809  Batman  1989.0
2152546  Batman  1989.0

[89 rows x 2 columns]

### How many roles were there in the movie "Inception"?

In [31]:
cast[cast["title"]=="Inception"]["character"].count()

52

### How many roles in the movie "Inception" are NOT ranked by an "n" value?

In [33]:
cast[(cast["title"]=="Inception") & (cast["n"].isna())]["character"].count()

21

### But how many roles in the movie "Inception" did receive an "n" value?

In [35]:
cast[(cast["title"]=="Inception") & (cast["n"].notna())]["character"].count()

31

### Display the cast of "North by Northwest" in their correct "n"-value order, ignoring roles that did not earn a numeric "n" value.

In [37]:
cast[(cast["title"]=="North by Northwest")& (cast["n"].notna())].sort_values(by="n")

,title,year,name,type,character,n
840374,North by Northwest,1959.0,Cary Grant,actor,Roger O. Thornhill,1.0
1404704,North by Northwest,1959.0,James Mason,actor,Phillip Vandamm,3.0
343701,North by Northwest,1959.0,Leo G. Carroll,actor,The Professor,5.0
1634552,North by Northwest,1959.0,Philip Ober,actor,Lester Townsend,7.0
1229083,North by Northwest,1959.0,Martin Landau,actor,Leonard,8.0
1746383,North by Northwest,1959.0,Edward Platt,actor,Victor Larrabee,10.0
642085,North by Northwest,1959.0,Robert Ellenstein,actor,Licht,11.0
447893,North by Northwest,1959.0,Philip Coolidge,actor,Dr. Cross,13.0
1454363,North by Northwest,1959.0,Patrick McVey,actor,Sergeant Flamm,14.0
198496,North by Northwest,1959.0,Edward Binns,actor,Captain Junket,15.0
1334726,North by Northwest,1959.0,Ken Lynch,actor,Charley - Chicago Policeman,16.0

### Display the entire cast, in "n"-order, of the 1972 film "Sleuth".

In [39]:
cast[(cast["title"]=="Sleuth") & (cast["year"]==1972)].sort_values(by="n")

,title,year,name,type,character,n
1644328,Sleuth,1972.0,Laurence Olivier,actor,Andrew Wyke,1.0
314691,Sleuth,1972.0,Michael Caine,actor,Milo Tindle,2.0
360365,Sleuth,1972.0,Alec Cawthorne,actor,Inspector Doppler,3.0
1412647,Sleuth,1972.0,John (II) Matthews,actor,Detective Sergeant Tarrant,4.0
1396572,Sleuth,1972.0,Teddy Martin,actor,Police Constable Higgs,6.0

In [40]:
cast[(cast["title"]=="Sleuth") & (cast["year"]==2007)].sort_values(by="n")

          title    year                 name   type          character    n
314692   Sleuth  2007.0        Michael Caine  actor             Andrew  1.0
1246855  Sleuth  2007.0             Jude Law  actor               Milo  2.0
1741124  Sleuth  2007.0        Harold Pinter  actor        Man on T.V.  3.0
250297   Sleuth  2007.0      Kenneth Branagh  actor  Other Man on T.V.  NaN
360366   Sleuth  2007.0  Alec (II) Cawthorne  actor  Inspector Doppler  NaN

### How many roles were credited in the silent 1921 version of Hamlet?

In [42]:
cast[(cast["title"]=="Hamlet") & (cast["year"]==1921)]["character"].count()

5

### How many roles were credited in Branagh’s 1996 Hamlet?

In [44]:
cast[(cast["title"]=="Hamlet") & (cast["year"]==1996)]["character"].count()

38

### How many "Hamlet" roles have been listed in all film credits through history?

In [46]:
cast[cast["title"]=="Hamlet"]["character"].count()

218

### How many people have played an "Ophelia"?

In [48]:
cast[cast["character"]=="Ophelia"]["name"].count()

7

### How many people have played a role called "The Dude"?

In [50]:
cast[cast["character"]=="The Dude"]["name"].count()

16

### How many people have played a role called "The Stranger"?

In [52]:
cast[cast["character"]=="The Stranger"]["name"].nunique()

173

### How many roles has Sidney Poitier played throughout his career?

In [54]:
cast[cast["name"]=="Sidney Poitier"]["character"].count()

43

### How many roles has Judi Dench played?

In [56]:
cast[cast["name"]=="Judi Dench"]["character"].count()

0

### List the supporting roles (having n=2) played by Cary Grant in the 1940s, in order by year.

In [58]:
cast[(cast["name"]=="Cary Grant") & (cast["n"]==2)].sort_values(by="year")

,title,year,name,type,character,n
840364,Madame Butterfly,1932.0,Cary Grant,actor,Lieutenant B.F. Pinkerton,2.0
840384,She Done Him Wrong,1933.0,Cary Grant,actor,Captain Cummings,2.0
840403,The Woman Accused,1933.0,Cary Grant,actor,Jeffrey Baxter,2.0
840395,The Eagle and the Hawk,1933.0,Cary Grant,actor,Henry Crocker,2.0
840358,I'm No Angel,1933.0,Cary Grant,actor,Jack Clayton,2.0
840404,Thirty Day Princess,1934.0,Cary Grant,actor,Porter Madison III,2.0
840339,Born to Be Bad,1934.0,Cary Grant,actor,Malcolm Trevor,2.0
840347,Enter Madame!,1935.0,Cary Grant,actor,Gerald Fitzgerald,2.0
840414,Wings in the Dark,1935.0,Cary Grant,actor,Ken Gordon,2.0
840388,Sylvia Scarlett,1936.0,Cary Grant,actor,Jimmy Monkley,2.0
840412,Wedding Present,1936.0,Cary Grant,actor,Charlie Mason,2.0
840413,When You're in Love,1937.0,Cary Grant,actor,Jimmy Hudson,2.0
840392,The Awful Truth,1937.0,Cary Grant,actor,Jerry Warriner,2.0
840402,The Toast of New York,1937.0,Cary Grant,actor,Nick Boyd,2.0
840408,Topper,1937.0,Cary Grant,actor,George Kerby,2.0
840354,Holiday,1938.0,Cary Grant,actor,Johnny Case,2.0
840340,Bringing Up Baby,1938.0,Cary Grant,actor,David,2.0
840359,In Name Only,1939.0,Cary Grant,actor,Alec Walker,2.0
840371,My Favorite Wife,1940.0,Cary Grant,actor,Nick,2.0
840381,Penny Serenade,1941.0,Cary Grant,actor,Roger Adams,2.0

### List the leading roles that Cary Grant played in the 1940s in order by year.

In [60]:
cast[(cast["name"]=="Cary Grant") & (cast["n"]==1)].sort_values(by="year")

,title,year,name,type,character,n
840355,Hot Saturday,1932.0,Cary Grant,actor,Romer Sheffield,1.0
840350,Gambling Ship,1933.0,Cary Grant,actor,Ace Corbin,1.0
840363,Ladies Should Listen,1934.0,Cary Grant,actor,Julian De Lussac,1.0
840361,Kiss and Make-Up,1934.0,Cary Grant,actor,Dr. Maurice Lamar,1.0
840398,The Last Outpost,1935.0,Cary Grant,actor,Michael Andrews,1.0
840391,The Amazing Quest of Ernest Bliss,1936.0,Cary Grant,actor,Ernest Bliss,1.0
840337,Big Brown Eyes,1936.0,Cary Grant,actor,Danny Barr,1.0
840379,Only Angels Have Wings,1939.0,Cary Grant,actor,Geoff Carter,1.0
840352,Gunga Din,1939.0,Cary Grant,actor,Cutter,1.0
840399,The Philadelphia Story,1940.0,Cary Grant,actor,C. K. Dexter Haven,1.0
840353,His Girl Friday,1940.0,Cary Grant,actor,Walter Burns,1.0
840397,The Howards of Virginia,1940.0,Cary Grant,actor,Matt Howard,1.0
840386,Suspicion,1941.0,Cary Grant,actor,Johnnie,1.0
840377,Once Upon a Honeymoon,1942.0,Cary Grant,actor,Patrick 'Pat' O'Toole,1.0
840401,The Talk of the Town,1942.0,Cary Grant,actor,Leopold Dilg,1.0
840370,Mr. Lucky,1943.0,Cary Grant,actor,Joe Bascopolous,1.0
840344,Destination Tokyo,1943.0,Cary Grant,actor,Capt. Cassidy,1.0
840369,Mr. Lucky,1943.0,Cary Grant,actor,Joe Adams,1.0
840336,Arsenic and Old Lace,1944.0,Cary Grant,actor,Mortimer Brewster,1.0
840378,Once Upon a Time,1944.0,Cary Grant,actor,Jerry Flynn,1.0
840373,None But the Lonely Heart,1944.0,Cary Grant,actor,Ernie Mott,1.0
840375,Notorious,1946.0,Cary Grant,actor,Devlin,1.0
840372,Night and Day,1946.0,Cary Grant,actor,Cole Porter,1.0
840394,The Bishop's Wife,1947.0,Cary Grant,actor,Dudley,1.0
840393,The Bachelor and the Bobby-Soxer,1947.0,Cary Grant,actor,Dick Nugent,1.0
840368,Mr. Blandings Builds His Dream House,1948.0,Cary Grant,actor,Jim Blandings,1.0
840348,Every Girl Should Be Married,1948.0,Cary Grant,actor,Dr. Madison Brown,1.0
840357,I Was a Male War Bride,1949.0,Cary Grant,actor,Captain Henri Rochard,1.0
840342,Crisis,1950.0,Cary Grant,actor,Dr. Eugene Norland Ferguson,1.0
840382,People Will Talk,1951.0,Cary Grant,actor,Dr. Noah Praetorius,1.0
840367,Monkey Business,1952.0,Cary Grant,actor,Dr. Barnaby Fulton,1.0
840383,Room for One More,1952.0,Cary Grant,actor,George Rose,1.0
840346,Dream Wife,1953.0,Cary Grant,actor,Clemson Reade,1.0
840407,To Catch a Thief,1955.0,Cary Grant,actor,John Robie,1.0
840400,The Pride and the Passion,1957.0,Cary Grant,actor,Anthony,1.0
840335,An Affair to Remember,1957.0,Cary Grant,actor,Nickie Ferrante,1.0
840362,Kiss Them for Me,1957.0,Cary Grant,actor,Cmdr. Andy Crewson,1.0
840360,Indiscreet,1958.0,Cary Grant,actor,Philip Adams,1.0
840356,Houseboat,1958.0,Cary Grant,actor,Tom Winters,1.0
840380,Operation Petticoat,1959.0,Cary Grant,actor,Lt. Cmdr. Matt T. Sherman,1.0
840374,North by Northwest,1959.0,Cary Grant,actor,Roger O. Thornhill,1.0
840396,The Grass Is Greener,1960.0,Cary Grant,actor,"Victor Rhyall, Earl",1.0
840389,That Touch of Mink,1962.0,Cary Grant,actor,Philip Shayne,1.0
840341,Charade,1963.0,Cary Grant,actor,Peter Joshua,1.0
840349,Father Goose,1964.0,Cary Grant,actor,Walter,1.0
840411,Walk Don't Run,1966.0,Cary Grant,actor,Sir William Rutland,1.0

### How many roles were available for actors in the 1950s?

In [62]:
cast[(cast["year"]>=1950) & (cast["year"]<1960) ]["character"].count()

137408

### How many leading roles (n=1) were available from the beginning of film history through 1980?

In [64]:
cast[(cast["n"]==1) & (cast["year"]<=1980)]["character"].count()

38187


### How many roles through 1980 were minor enough that they did not warrant a numeric "n" rank?

In [100]:
cast[cast["year"]<=1980]["n"].isna().sum()

299849